server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # 开启静态文件缓存
    open_file_cache max=1000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # 拦截常见的扫描路径
    location ~* ^/(config|init|ping|home|events|v1/config|im/v2|common/menus) {
        return 444;
    }

    # 拦截 .php, .env, .git 等敏感文件后缀
    location ~* \.(php|env|bak|config|sql|git|sh)$ {
        return 444;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }


    # 媒体文件缓存设置（视频、音频）
    location ~* \.(mp4|webm|ogg|mp3|wav)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        access_log off;
    }
    
    # 图片文件缓存设置
    location ~* \.(jpg|jpeg|png|gif|ico|svg|webp)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        access_log off;
    }
    
    # CSS、JavaScript文件缓存设置
    location ~* \.(css|js)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }
    
    # 字体文件缓存设置
    location ~* \.(woff|woff2|ttf|otf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        access_log off;
    }

    location /api/ {
        proxy_pass http://8.153.15.232:6666/;   # 后端服务地址
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Internal-Secret "fdcsky";
    }

    
}
