# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: score.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'score.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscore.proto\x12\x13\x66\x64u.kaoyanrank.grpc\"1\n\x0fGetScoreRequest\x12\x0e\n\x06\x65xamNo\x18\x01 \x01(\t\x12\x0e\n\x06idCard\x18\x02 \x01(\t\"\xb2\x01\n\x10GetScoreResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12I\n\ntotalScore\x18\x02 \x03(\x0b\x32\x35.fdu.kaoyanrank.grpc.GetScoreResponse.TotalScoreEntry\x12\x0f\n\x07message\x18\x03 \x01(\t\x1a\x31\n\x0fTotalScoreEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32i\n\x0cScoreService\x12Y\n\x08GetScore\x12$.fdu.kaoyanrank.grpc.GetScoreRequest\x1a%.fdu.kaoyanrank.grpc.GetScoreResponse\"\x00\x42#\n\x13\x66\x64u.kaoyanrank.grpcB\nScoreProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'score_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023fdu.kaoyanrank.grpcB\nScoreProtoP\001'
  _globals['_GETSCORERESPONSE_TOTALSCOREENTRY']._loaded_options = None
  _globals['_GETSCORERESPONSE_TOTALSCOREENTRY']._serialized_options = b'8\001'
  _globals['_GETSCOREREQUEST']._serialized_start=36
  _globals['_GETSCOREREQUEST']._serialized_end=85
  _globals['_GETSCORERESPONSE']._serialized_start=88
  _globals['_GETSCORERESPONSE']._serialized_end=266
  _globals['_GETSCORERESPONSE_TOTALSCOREENTRY']._serialized_start=217
  _globals['_GETSCORERESPONSE_TOTALSCOREENTRY']._serialized_end=266
  _globals['_SCORESERVICE']._serialized_start=268
  _globals['_SCORESERVICE']._serialized_end=373
# @@protoc_insertion_point(module_scope)
