server:
  port: 6666

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: kaoyan-rank-backend
  datasource:
    url: jdbc:mysql://8.153.15.232:3306/kaoyan_rank?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: tg852963
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 8.153.15.232
      port: 6379
      database: 0
      username: admin
      password: tg852963

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fdu.kaoyanrank.entity
  configuration:
    map-underscore-to-camel-case: true

app:
  hmac:
    secret: fdu_cs_kaoyan_rank
  ip-whitelist: "127.0.0.1"

grpc:
  client:
    scoreService:
      address: static://127.0.0.1:6667,127.0.0.1:6667
      negotiation-type: plaintext
      default-load-balancing-policy: round_robin
      keep-alive-time: 30s
      keep-alive-timeout: 10s
