server:
  port: ${SERVER_PORT:6666}

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: kaoyan-rank-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/kaoyan_rank?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      database: ${SPRING_DATA_REDIS_DATABASE:1}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: fdu.kaoyanrank.entity
  configuration:
    map-underscore-to-camel-case: true

app:
  hmac:
    secret: ${APP_HMAC_SECRET:change_me}
  ip-whitelist: "${APP_IP_WHITELIST:127.0.0.1}"

grpc:
  client:
    scoreService:
      address: ${GRPC_CLIENT_SCORE_SERVICE_ADDRESS:static://127.0.0.1:6667,127.0.0.1:6667}
      negotiation-type: plaintext
      default-load-balancing-policy: round_robin
      keep-alive-time: 30s
      keep-alive-timeout: 10s
